name: Test build procedure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Build libopus
      shell: bash
      working-directory: ${{github.workspace}}/opus
      run: |
        ./autogen.sh
        ./configure
        make -j12
        sudo make install

    - name: Build MoonJIT
      shell: bash
      working-directory: ${{github.workspace}}/moonjit/src
      run: sudo make XCFLAGS+=-DLUAJIT_ENABLE_LUA52COMPAT

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/release

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/release
      run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/release
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/test
      shell: bash
      run: ./test
